In [1]:
import numpy as np


In [2]:
arr1 = np.arange(1, 11)
arr2 = np.random.randint(1, 10, size=(3, 3))

arr1
arr2


array([[7, 6, 2],
       [2, 5, 8],
       [7, 1, 9]], dtype=int32)

In [3]:
arr1.sum(), arr1.mean(), arr1.max()


(np.int64(55), np.float64(5.5), np.int64(10))

In [4]:
arr1 * 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
np.where(arr1 > 5, 0, arr1)


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])